# Generated by Django 2.1.1 on 2020-08-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('featured', models.BooleanField()),
                ('slug', models.SlugField()),
                ('gitlab', models.CharField(blank=True, max_length=50)),
                ('categories', models.ManyToManyField(to='posts.Category')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Post')),
            ],
        ),
    ]
