# Generated by Django 2.1.1 on 2020-08-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gitlab',
            new_name='github',
        ),
    ]
