# Generated by Django 2.1.1 on 2020-08-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitlab',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
